name: release version

on:
  push:
    branches:
      - 20.0.1_orgs

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "--file=./keycloak-theme/pom.xml clean install -Dmaven.test.skip=true -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with:
          release-branch-name: "main"
          version-minor: true

          git-release-bot-name: "phasetwo-bot"
          git-release-bot-email: "support@phasetwo.io"

          maven-args: "--file=./keycloak-theme/pom.xml -B -Dmaven.test.skip=true -DskipITs -Dmaven.deploy.skip=true"

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: true
          gpg-key-id: BC6B4EADEB514AFD
          gpg-key: ${{ secrets.GPG_KEY }}

          docker-registry-id: ossrh
          docker-registry-username: ${{ secrets.OSSRH_USERNAME }}
          docker-registry-password: ${{ secrets.OSSRH_PASSWORD }}

          maven-development-version-number: 20.0.1.${parsedVersion.nextMinorVersion}-SNAPSHOT
          maven-release-version-number: 20.0.1.${parsedVersion.minorVersion}
